p8105_hw1_mc5296.Rmd
================
2022-09-15

# Problem1

## Load the dataset ‘penguins’

``` r
data("penguins", package = "palmerpenguins")
```

## Description of the dataset

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

There are penguins’ species,island and their bill length, bill depth,
flipper length,body mass,sex,and year in the dataset. There are 8
columns and 344 rows,so it is a 344\*8 dataset. The mean of flipper
length is 200.9 mm.

## scatter plot

``` r
library(ggplot2)
ggplot(data = penguins) + geom_point(mapping = aes(x = bill_length_mm, y = flipper_length_mm, color = species))
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_mc5296_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ✔ purrr   0.3.4      
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
df <- tibble(x1 = rnorm(10),
             vec_logical = (x1>0),
             vec_char = c("a","b","c","d","e","f","g","h","i","j"),
             vec_factor = factor(c("level1","level2","level3","level2","level1","level3","level1","level2","level1","level3"))
             )
df
```

    ## # A tibble: 10 × 4
    ##        x1 vec_logical vec_char vec_factor
    ##     <dbl> <lgl>       <chr>    <fct>     
    ##  1 -0.828 FALSE       a        level1    
    ##  2  2.28  TRUE        b        level2    
    ##  3  0.172 TRUE        c        level3    
    ##  4 -0.193 FALSE       d        level2    
    ##  5  1.17  TRUE        e        level1    
    ##  6  1.28  TRUE        f        level3    
    ##  7  0.911 TRUE        g        level1    
    ##  8  0.304 TRUE        h        level2    
    ##  9 -0.538 FALSE       i        level1    
    ## 10  1.31  TRUE        j        level3

``` r
mean(df$x1)
```

    ## [1] 0.5861298

``` r
mean(df$vec_logical)
```

    ## [1] 0.7

``` r
mean(df$vec_char)
```

    ## Warning in mean.default(df$vec_char): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(df$vec_factor)
```

    ## Warning in mean.default(df$vec_factor): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

The mean function works for random sample, logical vector, character
vector and doesn’t work for factor vector

## Convert Variable

``` r
as.numeric(df$x1)
as.numeric(df$vec_logical)
as.numeric(df$vec_char)
as.numeric(df$vec_factor)
```

The random sample, logical vector and factor vector can be converted to
vector while the character vector cannot. This is because elements in
random sample are mumerics, logical values can be represented by 0 and
1, factor can be converted to 1, 2, 3, 4… n according to the order in
the computer. But character cannot be converted because it is defined as
character so it cannot be converted to numeric.
